/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kano_grt_DTW */

#ifndef _Included_com_kano_grt_DTW
#define _Included_com_kano_grt_DTW
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kano_grt_DTW
 * Method:    instantiate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kano_grt_DTW_instantiate
  (JNIEnv *, jobject);

/*
 * Class:     com_kano_grt_DTW
 * Method:    trainNative
 * Signature: (Lcom/kano/grt/TimeSeriesClassificationData;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kano_grt_DTW_trainNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_kano_grt_DTW
 * Method:    predictNative
 * Signature: ([[D)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kano_grt_DTW_predictNative
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_kano_grt_DTW
 * Method:    getPredictedClassLabelNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kano_grt_DTW_getPredictedClassLabelNative
  (JNIEnv *, jobject);

/*
 * Class:     com_kano_grt_DTW
 * Method:    getMaximumLikelihoodNative
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_kano_grt_DTW_getMaximumLikelihoodNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
