/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kano_grt_TimeSeriesClassificationData */

#ifndef _Included_com_kano_grt_TimeSeriesClassificationData
#define _Included_com_kano_grt_TimeSeriesClassificationData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kano_grt_TimeSeriesClassificationData
 * Method:    instantiate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kano_grt_TimeSeriesClassificationData_instantiate
  (JNIEnv *, jobject);

/*
 * Class:     com_kano_grt_TimeSeriesClassificationData
 * Method:    setInfoTextNative
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kano_grt_TimeSeriesClassificationData_setInfoTextNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_kano_grt_TimeSeriesClassificationData
 * Method:    getInfoTextNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kano_grt_TimeSeriesClassificationData_getInfoTextNative
  (JNIEnv *, jobject);

/*
 * Class:     com_kano_grt_TimeSeriesClassificationData
 * Method:    setDatasetNameNative
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kano_grt_TimeSeriesClassificationData_setDatasetNameNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_kano_grt_TimeSeriesClassificationData
 * Method:    getDatasetNameNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kano_grt_TimeSeriesClassificationData_getDatasetNameNative
  (JNIEnv *, jobject);

/*
 * Class:     com_kano_grt_TimeSeriesClassificationData
 * Method:    setNumDimensionsNative
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kano_grt_TimeSeriesClassificationData_setNumDimensionsNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_kano_grt_TimeSeriesClassificationData
 * Method:    getNumDimensionsNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kano_grt_TimeSeriesClassificationData_getNumDimensionsNative
  (JNIEnv *, jobject);

/*
 * Class:     com_kano_grt_TimeSeriesClassificationData
 * Method:    getNumSamplesNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kano_grt_TimeSeriesClassificationData_getNumSamplesNative
  (JNIEnv *, jobject);

/*
 * Class:     com_kano_grt_TimeSeriesClassificationData
 * Method:    addSampleNative
 * Signature: (I[[D)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kano_grt_TimeSeriesClassificationData_addSampleNative
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
