/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kano_grt_HMM */

#ifndef _Included_com_kano_grt_HMM
#define _Included_com_kano_grt_HMM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kano_grt_HMM
 * Method:    instantiate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kano_grt_HMM_instantiate
  (JNIEnv *, jobject);

/*
 * Class:     com_kano_grt_HMM
 * Method:    trainNative
 * Signature: (Lcom/kano/grt/TimeSeriesClassificationData;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kano_grt_HMM_trainNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_kano_grt_HMM
 * Method:    predictNative
 * Signature: ([[D)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kano_grt_HMM_predictNative
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_kano_grt_HMM
 * Method:    getPredictedClassLabelNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kano_grt_HMM_getPredictedClassLabelNative
  (JNIEnv *, jobject);

/*
 * Class:     com_kano_grt_HMM
 * Method:    getClassLikelihoodsNative
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_kano_grt_HMM_getClassLikelihoodsNative
  (JNIEnv *, jobject);

/*
 * Class:     com_kano_grt_HMM
 * Method:    setHMMTypeNative
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kano_grt_HMM_setHMMTypeNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_kano_grt_HMM
 * Method:    setNumStatesNative
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kano_grt_HMM_setNumStatesNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_kano_grt_HMM
 * Method:    setNumSymbolsNative
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kano_grt_HMM_setNumSymbolsNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_kano_grt_HMM
 * Method:    setModelTypeNative
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kano_grt_HMM_setModelTypeNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_kano_grt_HMM
 * Method:    setMinChangeNative
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kano_grt_HMM_setMinChangeNative
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_kano_grt_HMM
 * Method:    setMaxNumEpochsNative
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kano_grt_HMM_setMaxNumEpochsNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_kano_grt_HMM
 * Method:    setNumRandomTrainingIterationsNative
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kano_grt_HMM_setNumRandomTrainingIterationsNative
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
